services:
  db:
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5431:5432"

  ads:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      ./wait-for-it.sh db:5432 -- ./start.sh
    depends_on:
      - db
    ports:
      - "80:8000"
    restart: always
